### ISSUE TITLE
Check calculation for write_image/write_bmp

### ISSUE THREAD

**Issue by kianmehre** [FLo-ABB/CognexNativePy#16]
I'm trying to write an image from my PC to the emulator to process it; however, the checksum seems to be causing issues.
I've manually uploaded the image to the emulator then read it, and the read binary data matches my input image (comparing by hashing the binary values). The length is half of the read data, so when I write, I double the length due to binary to hex conversion. However, I cannot get the checksum to match. Here is the function that I'm using which matches what Cognex is recommending on their official documentation:
```
def calculate_crc16(data: bytes) -> str:
# reference: https://support.cognex.com/docs/is_572/web/EN/ise/Content/Communications_Reference/Native_Mode_Checksum.htm?Highlight=checksum
    # Define the custom CRC-16 function using crcmod
    # Poly=0x11021 corresponds to polynomial x^16 + x^12 + x^5 + 1 (0x1021 with the implicit leading 1)
    # initCrc=0x0000, rev=False (MSB first), xorOut=0x0000 (no XOR out)
    crc_func = crcmod.mkCrcFun(poly=0x11021, initCrc=0x0000, rev=False, xorOut=0x0000)
    checksum = crc_func(data)
    return f"{checksum:04X}"
```
    
Despite this, the checksum does not match. I've verified a whole list of other checksum calculation methods, and none of them match. My input image is black and white; I've compared changing to 3 channels and also padding to be the default size of the HMI, and it still doesn't work. Are you aware of the proper way of calculating the checksum to be able to write an image or bmp? The function can be added to the utils as an improvement. An example usage would be great.

**Comment by FLo-ABB** [comment]
I've reviewed the documentation as well but I don't manage on getting the correct checksum calculation too! 🤔 Let's work together to figure this out! 💪
I noticed something interesting - when I use read_image, the size returned is twice the size of the file on my disk. This might be a helpful clue! 🔍

**Comment by kianmehre** [comment]
I noticed that as well which is why I double the length when writing image. This is due to binary to hex conversion that happens when you convert the image binary data to hex data that is 80 characters long.
There are a few conversions happening with added end of line characters that may be compromising the checksum. I've already spent a few hours trying to figure this out, but apparently that's not been enough!

**Comment by FLo-ABB** [comment]
I made it! 🚀🚀🚀

```
from CognexNativePy import NativeInterface


def calculate_checksum(buffer: bytes) -> int:
    """
    Calculate the CRC for the given buffer.

    Args:
        buffer (bytes): The input buffer.

    Returns:
        int: The calculated CRC value (unsigned short).
    """
    cword = 0  # Initialize CRC word
    for byte in buffer:
        ch = byte << 8  # Shift byte to the left by 8 bits
        for _ in range(8):  # Process each bit
            if ((ch & 0x8000) ^ (cword & 0x8000)):  # Check if MSB differs
                cword = (cword << 1) ^ 4129  # XOR with the polynomial
            else:
                cword <<= 1  # Shift left without XOR
            cword &= 0xFFFF  # Ensure cword stays within 16 bits
            ch <<= 1  # Shift ch to the left
    return cword


def hex_to_ascii_hex(buffer: bytes) -> bytes:
    """
    Convert a buffer to its ASCII hex representation.

    Args:
        buffer (bytes): The input buffer.

    Returns:
        bytes: The ASCII hex representation of the buffer.
    """
    return ''.join(f'{byte:02X}' for byte in buffer).encode('ascii')


def main():
    try:
        # Create a socket connection to the Cognex In-Sight vision system and log in
        native_interface = NativeInterface('192.168.56.1', 'admin', '')
        image = native_interface.image

        # Get the last image from the camera and save it as a BMP file
        dic = image.read_image()
        with open('testdata.txt', 'wb') as f:
            f.write(dic["data"])
        with open('testchecksum.txt', 'w') as f:
            f.write(dic["checksum"])
        with open('size.txt', 'w') as f:
            f.write(str(dic["size"]))

        with open("testdata.txt", "rb") as f:
            test_data = f.read()
        ascii_hex_data = hex_to_ascii_hex(test_data)
        print(f"Same length? {len(ascii_hex_data) == dic['size']}")
        checksum = calculate_checksum(ascii_hex_data)
        print(f"Same checksum? {hex(checksum).upper()[2:] == dic['checksum']}")

        # Close the socket connection
        native_interface.close()

    except Exception as e:
        print(f"Error: {e}")


if __name__ == '__main__':
    main()
```

**Comment by kianmehre** [comment]
It's great, thanks for digging into it. However, this is bitwise and slow to calculate. I will see if there is a way to speed it up with some of the built-in Python functions.
